# Configuration for NozzleNet ROS package

# Image processing settings
image_width: 224
image_height: 224
crop_top: 70
crop_bottom: 105

# Normalization settings
mean:
  - 0.4387
  - 0.4716
  - 0.4956
std:
  - 0.1933
  - 0.1992
  - 0.2179
