# Configuration for NozzleNet ROS package

# Image processing settings
image_width: 224
image_height: 224
crop_top: 0
crop_bottom: 110

# Model settings
model_path: model/resnet50.onnx

# Normalization settings
mean:
  - 0.485
  - 0.456
  - 0.406
std:
  - 0.229
  - 0.224
  - 0.225

